ALTER TABLE episode AUTO_INCREMENT=8;
ALTER TABLE film_person AUTO_INCREMENT=44;
ALTER TABLE gender AUTO_INCREMENT=11;
ALTER TABLE genre AUTO_INCREMENT=41;
ALTER TABLE genre_by_prod AUTO_INCREMENT=1;

ALTER TABLE movie AUTO_INCREMENT=62;
ALTER TABLE prod_in_platform AUTO_INCREMENT=62;
ALTER TABLE prod_company AUTO_INCREMENT=18;
ALTER TABLE prod_by_country AUTO_INCREMENT=1;
ALTER TABLE platform AUTO_INCREMENT=10;
ALTER TABLE person AUTO_INCREMENT=50;
ALTER TABLE partner_of AUTO_INCREMENT=2;
ALTER TABLE parent_of AUTO_INCREMENT=14;
ALTER TABLE identification_type AUTO_INCREMENT=4;
ALTER TABLE prod_by_company AUTO_INCREMENT=62;
ALTER TABLE production AUTO_INCREMENT=62;
ALTER TABLE production_crew AUTO_INCREMENT=17;
ALTER TABLE rol AUTO_INCREMENT=148;

SELECT `AUTO_INCREMENT`
FROM  INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'bd1'
AND   TABLE_NAME   = 'production';