select 'drop table ', table_name, 'cascade constraints;' from user_tables;

DROP SEQUENCE S_CAST_OF_PRODUCTION;
DROP SEQUENCE S_COUNTRY;
DROP SEQUENCE S_GENDER;
DROP SEQUENCE S_IDENTIFICATION_TYPE;
DROP SEQUENCE S_PERSON;
DROP SEQUENCE S_PLATFORM;
DROP SEQUENCE S_PROD_BY_COMPANY;
DROP SEQUENCE S_PROD_COMPANY;
DROP SEQUENCE S_USERR;
DROP SEQUENCE s_production;
DROP SEQUENCE s_genre;
DROP SEQUENCE s_genre_by_prod;
DROP SEQUENCE s_price_log;
DROP SEQUENCE s_idProdCompany;
DROP SEQUENCE s_idPlatform;
DROP SEQUENCE s_prod_in_platform;
DROP SEQUENCE s_movie;
DROP SEQUENCE s_series;
DROP SEQUENCE s_episode;
DROP SEQUENCE s_prod_by_country;
DROP SEQUENCE s_idCountry;
DROP SEQUENCE s_province;
DROP SEQUENCE s_city;
DROP SEQUENCE s_idPerson;
DROP SEQUENCE s_idGender;
DROP SEQUENCE s_parent_of;
DROP SEQUENCE s_partner_of;
DROP SEQUENCE s_rol;
DROP SEQUENCE s_film_person;
DROP SEQUENCE s_production_crew;
DROP SEQUENCE s_idUser;
DROP SEQUENCE s_administrator;
DROP SEQUENCE s_regular_user;
DROP SEQUENCE s_comentario;
DROP SEQUENCE s_review;
DROP SEQUENCE s_wish_list;
DROP SEQUENCE s_cart;
DROP SEQUENCE s_production_in_cart;
DROP SEQUENCE s_purchase;
DROP SEQUENCE s_payament_method;
DROP SEQUENCE s_production_image;
DROP SEQUENCE s_identification_type;


drop table 	PRODUCTION	cascade constraints;
drop table 	GENRE	cascade constraints;
drop table 	GENRE_BY_PROD	cascade constraints;
drop table 	PRICE_LOG	cascade constraints;
drop table 	PROD_COMPANY	cascade constraints;
drop table 	PROD_BY_COMPANY	cascade constraints;
drop table 	PLATFORM	cascade constraints;
drop table 	PROD_IN_PLATFORM	cascade constraints;
drop table 	MOVIE	cascade constraints;
drop table 	SERIES	cascade constraints;
drop table 	EPISODE	cascade constraints;
drop table 	PROD_BY_COUNTRY	cascade constraints;
drop table 	COUNTRY	cascade constraints;
drop table 	PROVINCE	cascade constraints;
drop table 	CITY	cascade constraints;
drop table 	PERSON	cascade constraints;
drop table 	GENDER	cascade constraints;
drop table 	PARENT_OF	cascade constraints;
drop table 	PARTNER_OF	cascade constraints;
drop table 	ROL	cascade constraints;
drop table 	FILM_PERSON	cascade constraints;
drop table 	PRODUCTION_CREW	cascade constraints;
drop table 	USERR	cascade constraints;
drop table 	ADMINISTRATOR	cascade constraints;
drop table 	REGULAR_USER	cascade constraints;
drop table 	COMENTARIO	cascade constraints;
drop table 	REVIEW	cascade constraints;
drop table 	WISH_LIST	cascade constraints;
drop table 	CART	cascade constraints;
drop table 	PRODUCTION_IN_CART	cascade constraints;
drop table 	PURCHASE	cascade constraints;
drop table 	PAYMENT_METHOD	cascade constraints;
drop table 	PRODUCTION_IMAGE	cascade constraints;
drop table 	IDENTIFICATION_TYPE	cascade constraints;
drop table 	CAST_OF_PRODUCTION	cascade constraints;
drop table 	PRODUCTION	cascade constraints;