SET DEFINE OFF



INSERT INTO PROD_BY_COMPANY (ID, ID_PRODUCTION, ID_COMPANY) 
VALUES (s_prod_by_company.nextval, 1, 3);

INSERT INTO PROD_BY_COMPANY (ID, ID_PRODUCTION, ID_COMPANY)  
VALUES (s_prod_by_company.nextval, 2, 3);

INSERT INTO PROD_BY_COMPANY (ID, ID_PRODUCTION, ID_COMPANY)  
VALUES (s_prod_by_company.nextval, 3, 4);

INSERT INTO PROD_BY_COMPANY (ID, ID_PRODUCTION, ID_COMPANY)  
VALUES (s_prod_by_company.nextval, 4, 7);

INSERT INTO PROD_BY_COMPANY (ID, ID_PRODUCTION, ID_COMPANY)  
VALUES (s_prod_by_company.nextval, 5, 3);

INSERT INTO PROD_BY_COMPANY (ID, ID_PRODUCTION, ID_COMPANY)  
VALUES (s_prod_by_company.nextval, 6, 16);

INSERT INTO PROD_BY_COMPANY (ID, ID_PRODUCTION, ID_COMPANY)  
VALUES (s_prod_by_company.nextval, 7, 3);

INSERT INTO PROD_BY_COMPANY (ID, ID_PRODUCTION, ID_COMPANY)  
VALUES (s_prod_by_company.nextval, 8, 8);

INSERT INTO PROD_BY_COMPANY (ID, ID_PRODUCTION, ID_COMPANY)  
VALUES (s_prod_by_company.nextval, 9, 7);

INSERT INTO PROD_BY_COMPANY (ID, ID_PRODUCTION, ID_COMPANY)  
VALUES (s_prod_by_company.nextval, 10, 7);

INSERT INTO PROD_BY_COMPANY (ID, ID_PRODUCTION, ID_COMPANY)  
VALUES (s_prod_by_company.nextval, 11, 7);

INSERT INTO PROD_BY_COMPANY (ID, ID_PRODUCTION, ID_COMPANY)  
VALUES (s_prod_by_company.nextval, 12, 7);

INSERT INTO PROD_BY_COMPANY (ID, ID_PRODUCTION, ID_COMPANY)  
VALUES (s_prod_by_company.nextval, 13, 3);

INSERT INTO PROD_BY_COMPANY (ID, ID_PRODUCTION, ID_COMPANY)  
VALUES (s_prod_by_company.nextval, 14, 3);

INSERT INTO PROD_BY_COMPANY (ID, ID_PRODUCTION, ID_COMPANY)  
VALUES (s_prod_by_company.nextval, 15, 7);

INSERT INTO PROD_BY_COMPANY (ID, ID_PRODUCTION, ID_COMPANY)  
VALUES (s_prod_by_company.nextval, 16, 3);

INSERT INTO PROD_BY_COMPANY (ID, ID_PRODUCTION, ID_COMPANY)  
VALUES (s_prod_by_company.nextval, 17, 8);

INSERT INTO PROD_BY_COMPANY (ID, ID_PRODUCTION, ID_COMPANY)  
VALUES (s_prod_by_company.nextval, 18, 3);

INSERT INTO PROD_BY_COMPANY (ID, ID_PRODUCTION, ID_COMPANY)  
VALUES (s_prod_by_company.nextval, 19, 16);

INSERT INTO PROD_BY_COMPANY (ID, ID_PRODUCTION, ID_COMPANY)  
VALUES (s_prod_by_company.nextval, 20, 9);

INSERT INTO PROD_BY_COMPANY (ID, ID_PRODUCTION, ID_COMPANY)  
VALUES (s_prod_by_company.nextval, 21, 16);

INSERT INTO PROD_BY_COMPANY (ID, ID_PRODUCTION, ID_COMPANY)  
VALUES (s_prod_by_company.nextval, 22, 5);

INSERT INTO PROD_BY_COMPANY (ID, ID_PRODUCTION, ID_COMPANY)  
VALUES (s_prod_by_company.nextval, 23, 9);

INSERT INTO PROD_BY_COMPANY (ID, ID_PRODUCTION, ID_COMPANY)  
VALUES (s_prod_by_company.nextval, 24, 11);

INSERT INTO PROD_BY_COMPANY (ID, ID_PRODUCTION, ID_COMPANY)  
VALUES (s_prod_by_company.nextval, 25, 5);

INSERT INTO PROD_BY_COMPANY (ID, ID_PRODUCTION, ID_COMPANY)  
VALUES (s_prod_by_company.nextval, 26, 6);

INSERT INTO PROD_BY_COMPANY (ID, ID_PRODUCTION, ID_COMPANY)  
VALUES (s_prod_by_company.nextval, 27, 8);

INSERT INTO PROD_BY_COMPANY (ID, ID_PRODUCTION, ID_COMPANY)  
VALUES (s_prod_by_company.nextval, 28, 5);

INSERT INTO PROD_BY_COMPANY (ID, ID_PRODUCTION, ID_COMPANY)  
VALUES (s_prod_by_company.nextval, 29, 5);

INSERT INTO PROD_BY_COMPANY (ID, ID_PRODUCTION, ID_COMPANY)  
VALUES (s_prod_by_company.nextval, 30, 4);

INSERT INTO PROD_BY_COMPANY (ID, ID_PRODUCTION, ID_COMPANY)  
VALUES (s_prod_by_company.nextval, 31, 16);

INSERT INTO PROD_BY_COMPANY (ID, ID_PRODUCTION, ID_COMPANY)  
VALUES (s_prod_by_company.nextval, 32, 8);

INSERT INTO PROD_BY_COMPANY (ID, ID_PRODUCTION, ID_COMPANY)  
VALUES (s_prod_by_company.nextval, 33, 3);

INSERT INTO PROD_BY_COMPANY (ID, ID_PRODUCTION, ID_COMPANY)  
VALUES (s_prod_by_company.nextval, 34, 8);

INSERT INTO PROD_BY_COMPANY (ID, ID_PRODUCTION, ID_COMPANY)  
VALUES (s_prod_by_company.nextval, 35, 10);

INSERT INTO PROD_BY_COMPANY (ID, ID_PRODUCTION, ID_COMPANY)  
VALUES (s_prod_by_company.nextval, 36, 12);

INSERT INTO PROD_BY_COMPANY (ID, ID_PRODUCTION, ID_COMPANY)  
VALUES (s_prod_by_company.nextval, 37, 12);

INSERT INTO PROD_BY_COMPANY (ID, ID_PRODUCTION, ID_COMPANY)  
VALUES (s_prod_by_company.nextval, 38, 3);

INSERT INTO PROD_BY_COMPANY (ID, ID_PRODUCTION, ID_COMPANY)  
VALUES (s_prod_by_company.nextval, 39, 16);

INSERT INTO PROD_BY_COMPANY (ID, ID_PRODUCTION, ID_COMPANY)  
VALUES (s_prod_by_company.nextval, 40, 3);

INSERT INTO PROD_BY_COMPANY (ID, ID_PRODUCTION, ID_COMPANY)  
VALUES (s_prod_by_company.nextval, 41, 10);

INSERT INTO PROD_BY_COMPANY (ID, ID_PRODUCTION, ID_COMPANY)  
VALUES (s_prod_by_company.nextval, 42, 7);

INSERT INTO PROD_BY_COMPANY (ID, ID_PRODUCTION, ID_COMPANY)  
VALUES (s_prod_by_company.nextval, 43, 10);

INSERT INTO PROD_BY_COMPANY (ID, ID_PRODUCTION, ID_COMPANY)  
VALUES (s_prod_by_company.nextval, 44, 4);

INSERT INTO PROD_BY_COMPANY (ID, ID_PRODUCTION, ID_COMPANY)  
VALUES (s_prod_by_company.nextval, 45, 5);

INSERT INTO PROD_BY_COMPANY (ID, ID_PRODUCTION, ID_COMPANY)  
VALUES (s_prod_by_company.nextval, 46, 14);

INSERT INTO PROD_BY_COMPANY (ID, ID_PRODUCTION, ID_COMPANY)  
VALUES (s_prod_by_company.nextval, 47, 6);

INSERT INTO PROD_BY_COMPANY (ID, ID_PRODUCTION, ID_COMPANY)  
VALUES (s_prod_by_company.nextval, 48, 14);

INSERT INTO PROD_BY_COMPANY (ID, ID_PRODUCTION, ID_COMPANY)  
VALUES (s_prod_by_company.nextval, 49, 11);

INSERT INTO PROD_BY_COMPANY (ID, ID_PRODUCTION, ID_COMPANY)  
VALUES (s_prod_by_company.nextval, 50, 7);

INSERT INTO PROD_BY_COMPANY (ID, ID_PRODUCTION, ID_COMPANY)  
VALUES (s_prod_by_company.nextval, 51, 3);

INSERT INTO PROD_BY_COMPANY (ID, ID_PRODUCTION, ID_COMPANY)  
VALUES (s_prod_by_company.nextval, 52, 15);

INSERT INTO PROD_BY_COMPANY (ID, ID_PRODUCTION, ID_COMPANY)  
VALUES (s_prod_by_company.nextval, 53, 17);

INSERT INTO PROD_BY_COMPANY (ID, ID_PRODUCTION, ID_COMPANY)  
VALUES (s_prod_by_company.nextval, 54, 17);

INSERT INTO PROD_BY_COMPANY (ID, ID_PRODUCTION, ID_COMPANY)  
VALUES (s_prod_by_company.nextval, 55, 17);

INSERT INTO PROD_BY_COMPANY (ID, ID_PRODUCTION, ID_COMPANY)  
VALUES (s_prod_by_company.nextval, 56, 17);

INSERT INTO PROD_BY_COMPANY (ID, ID_PRODUCTION, ID_COMPANY)  
VALUES (s_prod_by_company.nextval, 57, 17);

INSERT INTO PROD_BY_COMPANY (ID, ID_PRODUCTION, ID_COMPANY)  
VALUES (s_prod_by_company.nextval, 58, 17);

INSERT INTO PROD_BY_COMPANY (ID, ID_PRODUCTION, ID_COMPANY)  
VALUES (s_prod_by_company.nextval, 59, 17);

INSERT INTO PROD_BY_COMPANY (ID, ID_PRODUCTION, ID_COMPANY)  
VALUES (s_prod_by_company.nextval, 60, 17);

