SET DEFINE OFF

ALTER TABLE COUNTRY MODIFY (NAME VARCHAR2(2000));

INSERT INTO COUNTRY (ID, NAME) 
VALUES (1, 'Afghanistan');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (2, 'Aland Islands');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (3, 'Albania');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (4, 'Algeria');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (5, 'American Samoa');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (6, 'Andorra');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (7, 'Angola');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (8, 'Anguilla');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (9, 'Antarctica');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (10, 'Antigua and Barbuda');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (11, 'Argentina');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (12, 'Armenia');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (13, 'Aruba');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (14, 'Australia');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (15, 'Austria');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (16, 'Azerbaijan');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (18, 'Bahrain');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (19, 'Bangladesh');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (20, 'Barbados');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (21, 'Belarus');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (22, 'Belgium');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (23, 'Belize');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (24, 'Benin');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (25, 'Bermuda');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (26, 'Bhutan');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (27, 'Bolivia');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (155, 'Bonaire, Sint Eustatius and Saba');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (28, 'Bosnia and Herzegovina');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (29, 'Botswana');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (30, 'Bouvet Island');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (31, 'Brazil');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (32, 'British Indian Ocean Territory');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (33, 'Brunei');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (34, 'Bulgaria');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (35, 'Burkina Faso');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (36, 'Burundi');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (37, 'Cambodia');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (38, 'Cameroon');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (39, 'Canada');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (40, 'Cape Verde');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (41, 'Cayman Islands');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (42, 'Central African Republic');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (43, 'Chad');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (44, 'Chile');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (45, 'China');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (46, 'Christmas Island');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (47, 'Cocos (Keeling) Islands');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (48, 'Colombia');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (49, 'Comoros');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (50, 'Congo');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (52, 'Cook Islands');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (53, 'Costa Rica');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (54, 'Cote D''Ivoire (Ivory Coast)');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (55, 'Croatia');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (56, 'Cuba');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (249, 'Curaçao');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (57, 'Cyprus');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (58, 'Czech Republic');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (51, 'Democratic Republic of the Congo');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (59, 'Denmark');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (60, 'Djibouti');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (61, 'Dominica');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (62, 'Dominican Republic');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (64, 'Ecuador');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (65, 'Egypt');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (66, 'El Salvador');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (67, 'Equatorial Guinea');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (68, 'Eritrea');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (69, 'Estonia');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (212, 'Eswatini');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (70, 'Ethiopia');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (71, 'Falkland Islands');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (72, 'Faroe Islands');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (73, 'Fiji Islands');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (74, 'Finland');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (75, 'France');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (76, 'French Guiana');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (77, 'French Polynesia');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (78, 'French Southern Territories');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (79, 'Gabon');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (80, 'Gambia The');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (81, 'Georgia');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (82, 'Germany');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (83, 'Ghana');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (84, 'Gibraltar');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (85, 'Greece');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (86, 'Greenland');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (87, 'Grenada');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (88, 'Guadeloupe');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (89, 'Guam');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (90, 'Guatemala');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (91, 'Guernsey and Alderney');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (92, 'Guinea');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (93, 'Guinea-Bissau');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (94, 'Guyana');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (95, 'Haiti');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (96, 'Heard Island and McDonald Islands');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (97, 'Honduras');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (98, 'Hong Kong S.A.R.');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (99, 'Hungary');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (100, 'Iceland');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (101, 'India');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (102, 'Indonesia');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (103, 'Iran');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (104, 'Iraq');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (105, 'Ireland');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (106, 'Israel');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (107, 'Italy');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (108, 'Jamaica');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (109, 'Japan');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (110, 'Jersey');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (111, 'Jordan');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (112, 'Kazakhstan');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (113, 'Kenya');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (114, 'Kiribati');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (248, 'Kosovo');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (117, 'Kuwait');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (118, 'Kyrgyzstan');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (119, 'Laos');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (120, 'Latvia');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (121, 'Lebanon');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (122, 'Lesotho');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (123, 'Liberia');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (124, 'Libya');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (125, 'Liechtenstein');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (126, 'Lithuania');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (127, 'Luxembourg');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (128, 'Macau S.A.R.');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (130, 'Madagascar');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (131, 'Malawi');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (132, 'Malaysia');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (133, 'Maldives');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (134, 'Mali');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (135, 'Malta');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (136, 'Man (Isle of)');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (137, 'Marshall Islands');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (138, 'Martinique');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (139, 'Mauritania');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (140, 'Mauritius');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (141, 'Mayotte');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (142, 'Mexico');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (143, 'Micronesia');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (144, 'Moldova');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (145, 'Monaco');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (146, 'Mongolia');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (147, 'Montenegro');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (148, 'Montserrat');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (149, 'Morocco');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (150, 'Mozambique');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (151, 'Myanmar');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (152, 'Namibia');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (153, 'Nauru');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (154, 'Nepal');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (156, 'Netherlands');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (157, 'New Caledonia');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (158, 'New Zealand');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (159, 'Nicaragua');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (160, 'Niger');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (161, 'Nigeria');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (162, 'Niue');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (163, 'Norfolk Island');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (115, 'North Korea');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (129, 'North Macedonia');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (164, 'Northern Mariana Islands');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (165, 'Norway');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (166, 'Oman');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (167, 'Pakistan');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (168, 'Palau');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (169, 'Palestinian Territory Occupied');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (170, 'Panama');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (171, 'Papua New Guinea');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (172, 'Paraguay');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (173, 'Peru');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (174, 'Philippines');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (175, 'Pitcairn Island');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (176, 'Poland');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (177, 'Portugal');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (178, 'Puerto Rico');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (179, 'Qatar');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (180, 'Reunion');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (181, 'Romania');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (182, 'Russia');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (183, 'Rwanda');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (184, 'Saint Helena');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (185, 'Saint Kitts and Nevis');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (186, 'Saint Lucia');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (187, 'Saint Pierre and Miquelon');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (188, 'Saint Vincent and the Grenadines');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (189, 'Saint-Barthelemy');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (190, 'Saint-Martin (French part)');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (191, 'Samoa');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (192, 'San Marino');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (193, 'Sao Tome and Principe');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (194, 'Saudi Arabia');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (195, 'Senegal');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (196, 'Serbia');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (197, 'Seychelles');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (198, 'Sierra Leone');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (199, 'Singapore');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (250, 'Sint Maarten (Dutch part)');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (200, 'Slovakia');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (201, 'Slovenia');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (202, 'Solomon Islands');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (203, 'Somalia');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (204, 'South Africa');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (205, 'South Georgia');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (116, 'South Korea');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (206, 'South Sudan');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (207, 'Spain');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (208, 'Sri Lanka');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (209, 'Sudan');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (210, 'Suriname');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (211, 'Svalbard and Jan Mayen Islands');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (213, 'Sweden');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (214, 'Switzerland');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (215, 'Syria');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (216, 'Taiwan');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (217, 'Tajikistan');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (218, 'Tanzania');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (219, 'Thailand');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (17, 'The Bahamas');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (63, 'Timor-Leste');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (220, 'Togo');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (221, 'Tokelau');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (222, 'Tonga');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (223, 'Trinidad and Tobago');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (224, 'Tunisia');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (225, 'Turkey');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (226, 'Turkmenistan');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (227, 'Turks and Caicos Islands');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (228, 'Tuvalu');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (229, 'Uganda');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (230, 'Ukraine');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (231, 'United Arab Emirates');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (232, 'United Kingdom');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (233, 'United States');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (234, 'United States Minor Outlying Islands');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (235, 'Uruguay');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (236, 'Uzbekistan');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (237, 'Vanuatu');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (238, 'Vatican City State (Holy See)');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (239, 'Venezuela');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (240, 'Vietnam');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (241, 'Virgin Islands (British)');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (242, 'Virgin Islands (US)');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (243, 'Wallis and Futuna Islands');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (244, 'Western Sahara');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (245, 'Yemen');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (246, 'Zambia');

INSERT INTO COUNTRY (ID, NAME) 
VALUES (247, 'Zimbabwe');

DROP SEQUENCE s_country;

CREATE SEQUENCE s_country
start with 250
increment by 1
minvalue 1
maxvalue 9999
cache 2
order
nocycle;