--Insert failed for rows  1  through  60 
--ORA-01400: cannot insert NULL into ("PRY"."PROD_BY_COUNTRY"."ID")
--Row 1
INSERT INTO PROD_BY_COUNTRY ( ID, ID_PRODUCTION, ID_COUNTRY) VALUES ( S_PROD_BY_COUNTRY.NEXTVAL, 1,233);
--Row 2
INSERT INTO PROD_BY_COUNTRY ( ID, ID_PRODUCTION, ID_COUNTRY) VALUES ( S_PROD_BY_COUNTRY.NEXTVAL, 2,233);
--Row 3
INSERT INTO PROD_BY_COUNTRY ( ID, ID_PRODUCTION, ID_COUNTRY) VALUES ( S_PROD_BY_COUNTRY.NEXTVAL, 3,232);
--Row 4
INSERT INTO PROD_BY_COUNTRY ( ID, ID_PRODUCTION, ID_COUNTRY) VALUES ( S_PROD_BY_COUNTRY.NEXTVAL, 4,233);
--Row 5
INSERT INTO PROD_BY_COUNTRY ( ID, ID_PRODUCTION, ID_COUNTRY) VALUES ( S_PROD_BY_COUNTRY.NEXTVAL, 5,233);
--Row 6
INSERT INTO PROD_BY_COUNTRY ( ID, ID_PRODUCTION, ID_COUNTRY) VALUES ( S_PROD_BY_COUNTRY.NEXTVAL, 6,233);
--Row 7
INSERT INTO PROD_BY_COUNTRY ( ID, ID_PRODUCTION, ID_COUNTRY) VALUES ( S_PROD_BY_COUNTRY.NEXTVAL, 7,233);
--Row 8
INSERT INTO PROD_BY_COUNTRY ( ID, ID_PRODUCTION, ID_COUNTRY) VALUES ( S_PROD_BY_COUNTRY.NEXTVAL, 8,233);
--Row 9
INSERT INTO PROD_BY_COUNTRY ( ID, ID_PRODUCTION, ID_COUNTRY) VALUES ( S_PROD_BY_COUNTRY.NEXTVAL, 9,232);
--Row 10
INSERT INTO PROD_BY_COUNTRY ( ID, ID_PRODUCTION, ID_COUNTRY) VALUES ( S_PROD_BY_COUNTRY.NEXTVAL, 10,233);
--Row 11
INSERT INTO PROD_BY_COUNTRY ( ID, ID_PRODUCTION, ID_COUNTRY) VALUES ( S_PROD_BY_COUNTRY.NEXTVAL, 11,233);
--Row 12
INSERT INTO PROD_BY_COUNTRY ( ID, ID_PRODUCTION, ID_COUNTRY) VALUES ( S_PROD_BY_COUNTRY.NEXTVAL, 12,232);
--Row 13
INSERT INTO PROD_BY_COUNTRY ( ID, ID_PRODUCTION, ID_COUNTRY) VALUES ( S_PROD_BY_COUNTRY.NEXTVAL, 13,233);
--Row 14
INSERT INTO PROD_BY_COUNTRY ( ID, ID_PRODUCTION, ID_COUNTRY) VALUES ( S_PROD_BY_COUNTRY.NEXTVAL, 14,233);
--Row 15
INSERT INTO PROD_BY_COUNTRY ( ID, ID_PRODUCTION, ID_COUNTRY) VALUES ( S_PROD_BY_COUNTRY.NEXTVAL, 15,233);
--Row 16
INSERT INTO PROD_BY_COUNTRY ( ID, ID_PRODUCTION, ID_COUNTRY) VALUES ( S_PROD_BY_COUNTRY.NEXTVAL, 16,233);
--Row 17
INSERT INTO PROD_BY_COUNTRY ( ID, ID_PRODUCTION, ID_COUNTRY) VALUES ( S_PROD_BY_COUNTRY.NEXTVAL, 17,233);
--Row 18
INSERT INTO PROD_BY_COUNTRY ( ID, ID_PRODUCTION, ID_COUNTRY) VALUES ( S_PROD_BY_COUNTRY.NEXTVAL, 18,233);
--Row 19
INSERT INTO PROD_BY_COUNTRY ( ID, ID_PRODUCTION, ID_COUNTRY) VALUES ( S_PROD_BY_COUNTRY.NEXTVAL, 19,233);
--Row 20
INSERT INTO PROD_BY_COUNTRY ( ID, ID_PRODUCTION, ID_COUNTRY) VALUES ( S_PROD_BY_COUNTRY.NEXTVAL, 20,158);
--Row 21
INSERT INTO PROD_BY_COUNTRY ( ID, ID_PRODUCTION, ID_COUNTRY) VALUES ( S_PROD_BY_COUNTRY.NEXTVAL, 21,233);
--Row 22
INSERT INTO PROD_BY_COUNTRY ( ID, ID_PRODUCTION, ID_COUNTRY) VALUES ( S_PROD_BY_COUNTRY.NEXTVAL, 22,233);
--Row 23
INSERT INTO PROD_BY_COUNTRY ( ID, ID_PRODUCTION, ID_COUNTRY) VALUES ( S_PROD_BY_COUNTRY.NEXTVAL, 23,158);
--Row 24
INSERT INTO PROD_BY_COUNTRY ( ID, ID_PRODUCTION, ID_COUNTRY) VALUES ( S_PROD_BY_COUNTRY.NEXTVAL, 24,233);
--Row 25
INSERT INTO PROD_BY_COUNTRY ( ID, ID_PRODUCTION, ID_COUNTRY) VALUES ( S_PROD_BY_COUNTRY.NEXTVAL, 25,233);
--Row 26
INSERT INTO PROD_BY_COUNTRY ( ID, ID_PRODUCTION, ID_COUNTRY) VALUES ( S_PROD_BY_COUNTRY.NEXTVAL, 26,233);
--Row 27
INSERT INTO PROD_BY_COUNTRY ( ID, ID_PRODUCTION, ID_COUNTRY) VALUES ( S_PROD_BY_COUNTRY.NEXTVAL, 27,233);
--Row 28
INSERT INTO PROD_BY_COUNTRY ( ID, ID_PRODUCTION, ID_COUNTRY) VALUES ( S_PROD_BY_COUNTRY.NEXTVAL, 28,233);
--Row 29
INSERT INTO PROD_BY_COUNTRY ( ID, ID_PRODUCTION, ID_COUNTRY) VALUES ( S_PROD_BY_COUNTRY.NEXTVAL, 29,233);
--Row 30
INSERT INTO PROD_BY_COUNTRY ( ID, ID_PRODUCTION, ID_COUNTRY) VALUES ( S_PROD_BY_COUNTRY.NEXTVAL, 30,232);
--Row 31
INSERT INTO PROD_BY_COUNTRY ( ID, ID_PRODUCTION, ID_COUNTRY) VALUES ( S_PROD_BY_COUNTRY.NEXTVAL, 31,233);
--Row 32
INSERT INTO PROD_BY_COUNTRY ( ID, ID_PRODUCTION, ID_COUNTRY) VALUES ( S_PROD_BY_COUNTRY.NEXTVAL, 32,233);
--Row 33
INSERT INTO PROD_BY_COUNTRY ( ID, ID_PRODUCTION, ID_COUNTRY) VALUES ( S_PROD_BY_COUNTRY.NEXTVAL, 33,233);
--Row 34
INSERT INTO PROD_BY_COUNTRY ( ID, ID_PRODUCTION, ID_COUNTRY) VALUES ( S_PROD_BY_COUNTRY.NEXTVAL, 34,233);
--Row 35
INSERT INTO PROD_BY_COUNTRY ( ID, ID_PRODUCTION, ID_COUNTRY) VALUES ( S_PROD_BY_COUNTRY.NEXTVAL, 35,233);
--Row 36
INSERT INTO PROD_BY_COUNTRY ( ID, ID_PRODUCTION, ID_COUNTRY) VALUES ( S_PROD_BY_COUNTRY.NEXTVAL, 36,233);
--Row 37
INSERT INTO PROD_BY_COUNTRY ( ID, ID_PRODUCTION, ID_COUNTRY) VALUES ( S_PROD_BY_COUNTRY.NEXTVAL, 37,233);
--Row 38
INSERT INTO PROD_BY_COUNTRY ( ID, ID_PRODUCTION, ID_COUNTRY) VALUES ( S_PROD_BY_COUNTRY.NEXTVAL, 38,233);
--Row 39
INSERT INTO PROD_BY_COUNTRY ( ID, ID_PRODUCTION, ID_COUNTRY) VALUES ( S_PROD_BY_COUNTRY.NEXTVAL, 39,233);
--Row 40
INSERT INTO PROD_BY_COUNTRY ( ID, ID_PRODUCTION, ID_COUNTRY) VALUES ( S_PROD_BY_COUNTRY.NEXTVAL, 40,233);
--Row 41
INSERT INTO PROD_BY_COUNTRY ( ID, ID_PRODUCTION, ID_COUNTRY) VALUES ( S_PROD_BY_COUNTRY.NEXTVAL, 41,233);
--Row 42
INSERT INTO PROD_BY_COUNTRY ( ID, ID_PRODUCTION, ID_COUNTRY) VALUES ( S_PROD_BY_COUNTRY.NEXTVAL, 42,233);
--Row 43
INSERT INTO PROD_BY_COUNTRY ( ID, ID_PRODUCTION, ID_COUNTRY) VALUES ( S_PROD_BY_COUNTRY.NEXTVAL, 43,233);
--Row 44
INSERT INTO PROD_BY_COUNTRY ( ID, ID_PRODUCTION, ID_COUNTRY) VALUES ( S_PROD_BY_COUNTRY.NEXTVAL, 44,233);
--Row 45
INSERT INTO PROD_BY_COUNTRY ( ID, ID_PRODUCTION, ID_COUNTRY) VALUES ( S_PROD_BY_COUNTRY.NEXTVAL, 45,233);
--Row 46
INSERT INTO PROD_BY_COUNTRY ( ID, ID_PRODUCTION, ID_COUNTRY) VALUES ( S_PROD_BY_COUNTRY.NEXTVAL, 46,233);
--Row 47
INSERT INTO PROD_BY_COUNTRY ( ID, ID_PRODUCTION, ID_COUNTRY) VALUES ( S_PROD_BY_COUNTRY.NEXTVAL, 47,233);
--Row 48
INSERT INTO PROD_BY_COUNTRY ( ID, ID_PRODUCTION, ID_COUNTRY) VALUES ( S_PROD_BY_COUNTRY.NEXTVAL, 48,233);
--Row 49
INSERT INTO PROD_BY_COUNTRY ( ID, ID_PRODUCTION, ID_COUNTRY) VALUES ( S_PROD_BY_COUNTRY.NEXTVAL, 49,233);
--Row 50
INSERT INTO PROD_BY_COUNTRY ( ID, ID_PRODUCTION, ID_COUNTRY) VALUES ( S_PROD_BY_COUNTRY.NEXTVAL, 50,233);
--Row 51
INSERT INTO PROD_BY_COUNTRY ( ID, ID_PRODUCTION, ID_COUNTRY) VALUES ( S_PROD_BY_COUNTRY.NEXTVAL, 51,233);
--Row 52
INSERT INTO PROD_BY_COUNTRY ( ID, ID_PRODUCTION, ID_COUNTRY) VALUES ( S_PROD_BY_COUNTRY.NEXTVAL, 52,232);
--Row 53
INSERT INTO PROD_BY_COUNTRY ( ID, ID_PRODUCTION, ID_COUNTRY) VALUES ( S_PROD_BY_COUNTRY.NEXTVAL, 53,207);
--Row 54
INSERT INTO PROD_BY_COUNTRY ( ID, ID_PRODUCTION, ID_COUNTRY) VALUES ( S_PROD_BY_COUNTRY.NEXTVAL, 54,232);
--Row 55
INSERT INTO PROD_BY_COUNTRY ( ID, ID_PRODUCTION, ID_COUNTRY) VALUES ( S_PROD_BY_COUNTRY.NEXTVAL, 55,232);
--Row 56
INSERT INTO PROD_BY_COUNTRY ( ID, ID_PRODUCTION, ID_COUNTRY) VALUES ( S_PROD_BY_COUNTRY.NEXTVAL, 56,232);
--Row 57
INSERT INTO PROD_BY_COUNTRY ( ID, ID_PRODUCTION, ID_COUNTRY) VALUES ( S_PROD_BY_COUNTRY.NEXTVAL, 57,232);
--Row 58
INSERT INTO PROD_BY_COUNTRY ( ID, ID_PRODUCTION, ID_COUNTRY) VALUES ( S_PROD_BY_COUNTRY.NEXTVAL, 58,232);
--Row 59
INSERT INTO PROD_BY_COUNTRY ( ID, ID_PRODUCTION, ID_COUNTRY) VALUES ( S_PROD_BY_COUNTRY.NEXTVAL, 59,232);
--Row 60
INSERT INTO PROD_BY_COUNTRY ( ID, ID_PRODUCTION, ID_COUNTRY) VALUES ( S_PROD_BY_COUNTRY.NEXTVAL, 60,232);
