SET DEFINE OFF



INSERT INTO PERSON (ID, BIRTHDATE, FIRST_NAME, LAST_NAME, GENDER) 
VALUES (13, to_date('3/1/1970', 'DD/MM/YYYY'), 'Anthony', 'Russo', 2);

INSERT INTO PERSON (ID, BIRTHDATE, FIRST_NAME, LAST_NAME, GENDER) 
VALUES (14, to_date('1/4/1953', 'DD/MM/YYYY'), 'Barry', 'Sonnenfeld', 2);

INSERT INTO PERSON (ID, BIRTHDATE, FIRST_NAME, LAST_NAME, GENDER) 
VALUES (15, to_date('17/09/1962', 'DD/MM/YYYY'), 'Baz', 'Luhrmann', 2);

INSERT INTO PERSON (ID, BIRTHDATE, FIRST_NAME, LAST_NAME, GENDER) 
VALUES (16, to_date('28/03/1969', 'DD/MM/YYYY'), 'Brett', 'Ratner', 2);

INSERT INTO PERSON (ID, BIRTHDATE, FIRST_NAME, LAST_NAME, GENDER) 
VALUES (17, to_date('17/09/1965', 'DD/MM/YYYY'), 'Bryan', 'Singer', 2);

INSERT INTO PERSON (ID, BIRTHDATE, FIRST_NAME, LAST_NAME, GENDER) 
VALUES (18, to_date('30/11/1969', 'DD/MM/YYYY'), 'Chris', 'Weitz', 2);

INSERT INTO PERSON (ID, BIRTHDATE, FIRST_NAME, LAST_NAME, GENDER) 
VALUES (19, to_date('30/06/1970', 'DD/MM/YYYY'), 'Christopher', 'Nolan', 2);

INSERT INTO PERSON (ID, BIRTHDATE, FIRST_NAME, LAST_NAME, GENDER) 
VALUES (20, to_date('13/09/1976', 'DD/MM/YYYY'), 'Colin', 'Trevorrow', 2);

INSERT INTO PERSON (ID, BIRTHDATE, FIRST_NAME, LAST_NAME, GENDER) 
VALUES (21, to_date('21/06/1976', 'DD/MM/YYYY'), 'Dan', 'Scanlon', 2);

INSERT INTO PERSON (ID, BIRTHDATE, FIRST_NAME, LAST_NAME, GENDER) 
VALUES (22, to_date('8/10/1963', 'DD/MM/YYYY'), 'David', 'Yates', 2);

INSERT INTO PERSON (ID, BIRTHDATE, FIRST_NAME, LAST_NAME, GENDER) 
VALUES (23, to_date('16/03/1964', 'DD/MM/YYYY'), 'Gore', 'Verbinski', 2);

INSERT INTO PERSON (ID, BIRTHDATE, FIRST_NAME, LAST_NAME, GENDER) 
VALUES (24, to_date('27/06/1966', 'DD/MM/YYYY'), 'Jeffrey Jacob','Abrams',  2);

INSERT INTO PERSON (ID, BIRTHDATE, FIRST_NAME, LAST_NAME, GENDER) 
VALUES (25, to_date('16/08/1954', 'DD/MM/YYYY'),  'James', 'Cameron',2);

INSERT INTO PERSON (ID, BIRTHDATE, FIRST_NAME, LAST_NAME, GENDER) 
VALUES (26, to_date('26/02/1977', 'DD/MM/YYYY'), 'James', 'Wan', 2);

INSERT INTO PERSON (ID, BIRTHDATE, FIRST_NAME, LAST_NAME, GENDER) 
VALUES (27, to_date('12/1/1957', 'DD/MM/YYYY'), 'John', 'Lasseter', 2);

INSERT INTO PERSON (ID, BIRTHDATE, FIRST_NAME, LAST_NAME, GENDER) 
VALUES (28, to_date('31/08/1974', 'DD/MM/YYYY'), 'Marc', 'Webb', 2);

INSERT INTO PERSON (ID, BIRTHDATE, FIRST_NAME, LAST_NAME, GENDER) 
VALUES (29, to_date('11/3/1964', 'DD/MM/YYYY'),  'Peter', 'Berg',2);

INSERT INTO PERSON (ID, BIRTHDATE, FIRST_NAME, LAST_NAME, GENDER) 
VALUES (30, to_date('1/3/1966', 'DD/MM/YYYY'), 'Zack','Snyder',  2);

INSERT INTO PERSON (ID, BIRTHDATE, FIRST_NAME, LAST_NAME, GENDER) 
VALUES (31, to_date('25/08/1976', 'DD/MM/YYYY'), 'Alexander', 'Skarsgard', 2);

INSERT INTO PERSON (ID, BIRTHDATE, FIRST_NAME, LAST_NAME, GENDER) 
VALUES (32, to_date('20/08/1983', 'DD/MM/YYYY'), 'Andrew', 'Garfield', 2);

INSERT INTO PERSON (ID, BIRTHDATE, FIRST_NAME, LAST_NAME, GENDER) 
VALUES (33, to_date('15/08/1972', 'DD/MM/YYYY'), 'Ben', 'Affleck', 2);

INSERT INTO PERSON (ID, BIRTHDATE, FIRST_NAME, LAST_NAME, GENDER) 
VALUES (34, to_date('20/08/1981', 'DD/MM/YYYY'), 'Ben', 'Barnes', 2);

INSERT INTO PERSON (ID, BIRTHDATE, FIRST_NAME, LAST_NAME, GENDER) 
VALUES (35, to_date('14/03/1948', 'DD/MM/YYYY'), 'Billy', 'Crystal', 2);

INSERT INTO PERSON (ID, BIRTHDATE, FIRST_NAME, LAST_NAME, GENDER) 
VALUES (36, to_date('1/12/1966', 'DD/MM/YYYY'), 'Andrew','Adamson',  2);

INSERT INTO PERSON (ID, BIRTHDATE, FIRST_NAME, LAST_NAME, GENDER) 
VALUES (37, to_date('31/03/1972', 'DD/MM/YYYY'), 'Alejandro', 'Almenabar', 4);

INSERT INTO PERSON (ID, BIRTHDATE, FIRST_NAME, LAST_NAME, GENDER) 
VALUES (38, to_date('12/01/1949', 'DD/MM/YYYY'), 'Wayne', 'Wang', 2);

INSERT INTO PERSON (ID, BIRTHDATE, FIRST_NAME, LAST_NAME, GENDER) 
VALUES (39, to_date('09/03/1954', 'DD/MM/YYYY'), 'Kevin', 'Wade', 2);

INSERT INTO PERSON (ID, BIRTHDATE, FIRST_NAME, LAST_NAME, GENDER) 
VALUES (40, to_date('24/06/1969', 'DD/MM/YYYY'), 'Jennifer', 'Lopez', 3);

INSERT INTO PERSON (ID, BIRTHDATE, FIRST_NAME, LAST_NAME, GENDER) 
VALUES (41, to_date('12/01/1949', 'DD/MM/YYYY'), 'Ralph', 'Fiennes', 2);

INSERT INTO PERSON (ID, BIRTHDATE, FIRST_NAME, LAST_NAME, GENDER) 
VALUES (42, to_date('11/05/1963', 'DD/MM/YYYY'), 'Natasha', 'Richardson', 2);

INSERT INTO PERSON (ID, BIRTHDATE, FIRST_NAME, LAST_NAME, GENDER) 
VALUES (43, to_date('11/12/1960', 'DD/MM/YYYY'), 'Stanley', 'Tucci', 2);

INSERT INTO PERSON (ID, BIRTHDATE, FIRST_NAME, LAST_NAME, GENDER) 
VALUES (44, to_date('18/02/1950', 'DD/MM/YYYY'), 'John', 'Hughes', 2);

INSERT INTO PERSON (ID, BIRTHDATE, FIRST_NAME, LAST_NAME, GENDER) 
VALUES (45, to_date('22/02/2002', 'DD/MM/YYYY'), 'Emme', 'Muñiz', 2);

INSERT INTO PERSON (ID, BIRTHDATE, FIRST_NAME, LAST_NAME, GENDER) 
VALUES (46, to_date('27/02/2012', 'DD/MM/YYYY'), 'Samuel', 'Garner Affleck', 2);

INSERT INTO PERSON (ID, BIRTHDATE, FIRST_NAME, LAST_NAME, GENDER) 
VALUES (47, to_date('6/01/2009', 'DD/MM/YYYY'), 'Seraphina', 'Affleck', 2);

INSERT INTO PERSON (ID, BIRTHDATE, FIRST_NAME, LAST_NAME, GENDER) 
VALUES (48, to_date('1/12/2005', 'DD/MM/YYYY'), 'Violet', 'Affleck', 2);

INSERT INTO PERSON (ID, BIRTHDATE, FIRST_NAME, LAST_NAME, GENDER) 
VALUES (49, to_date('22/02/2008', 'DD/MM/YYYY'), 'Max', 'Muñiz', 2);



DROP SEQUENCE s_person;

CREATE SEQUENCE s_person
start with 43
increment by 1
minvalue 1
maxvalue 9999
cache 2
order
nocycle;