SET DEFINE OFF

INSERT INTO PROD_IN_PLATFORM (ID, ID_PRODUCTION, ID_PLATFORM) 
VALUES (S_PROD_IN_PLATFORM.NEXTVAL, 1, 6);

INSERT INTO PROD_IN_PLATFORM (ID, ID_PRODUCTION, ID_PLATFORM) 
VALUES (S_PROD_IN_PLATFORM.NEXTVAL, 2, 6);

INSERT INTO PROD_IN_PLATFORM (ID, ID_PRODUCTION, ID_PLATFORM) 
VALUES (S_PROD_IN_PLATFORM.NEXTVAL, 3, 5);

INSERT INTO PROD_IN_PLATFORM (ID, ID_PRODUCTION, ID_PLATFORM) 
VALUES (S_PROD_IN_PLATFORM.NEXTVAL, 4, 3);

INSERT INTO PROD_IN_PLATFORM (ID, ID_PRODUCTION, ID_PLATFORM) 
VALUES (S_PROD_IN_PLATFORM.NEXTVAL, 5, 6);

INSERT INTO PROD_IN_PLATFORM (ID, ID_PRODUCTION, ID_PLATFORM) 
VALUES (S_PROD_IN_PLATFORM.NEXTVAL, 6, 5);

INSERT INTO PROD_IN_PLATFORM (ID, ID_PRODUCTION, ID_PLATFORM) 
VALUES (S_PROD_IN_PLATFORM.NEXTVAL, 7, 6);

INSERT INTO PROD_IN_PLATFORM (ID, ID_PRODUCTION, ID_PLATFORM) 
VALUES (S_PROD_IN_PLATFORM.NEXTVAL, 8, 6);

INSERT INTO PROD_IN_PLATFORM (ID, ID_PRODUCTION, ID_PLATFORM) 
VALUES (S_PROD_IN_PLATFORM.NEXTVAL, 9, 3);

INSERT INTO PROD_IN_PLATFORM (ID, ID_PRODUCTION, ID_PLATFORM) 
VALUES (S_PROD_IN_PLATFORM.NEXTVAL, 10, 3);

INSERT INTO PROD_IN_PLATFORM (ID, ID_PRODUCTION, ID_PLATFORM) 
VALUES (S_PROD_IN_PLATFORM.NEXTVAL, 11, 3);

INSERT INTO PROD_IN_PLATFORM (ID, ID_PRODUCTION, ID_PLATFORM) 
VALUES (S_PROD_IN_PLATFORM.NEXTVAL, 12, 3);

INSERT INTO PROD_IN_PLATFORM (ID, ID_PRODUCTION, ID_PLATFORM) 
VALUES (S_PROD_IN_PLATFORM.NEXTVAL, 13, 6);

INSERT INTO PROD_IN_PLATFORM (ID, ID_PRODUCTION, ID_PLATFORM) 
VALUES (S_PROD_IN_PLATFORM.NEXTVAL, 14, 6);

INSERT INTO PROD_IN_PLATFORM (ID, ID_PRODUCTION, ID_PLATFORM) 
VALUES (S_PROD_IN_PLATFORM.NEXTVAL, 15, 3);

INSERT INTO PROD_IN_PLATFORM (ID, ID_PRODUCTION, ID_PLATFORM) 
VALUES (S_PROD_IN_PLATFORM.NEXTVAL, 16, 6);

INSERT INTO PROD_IN_PLATFORM (ID, ID_PRODUCTION, ID_PLATFORM) 
VALUES (S_PROD_IN_PLATFORM.NEXTVAL, 17, 6);

INSERT INTO PROD_IN_PLATFORM (ID, ID_PRODUCTION, ID_PLATFORM) 
VALUES (S_PROD_IN_PLATFORM.NEXTVAL, 18, 6);

INSERT INTO PROD_IN_PLATFORM (ID, ID_PRODUCTION, ID_PLATFORM) 
VALUES (S_PROD_IN_PLATFORM.NEXTVAL, 19, 5);

INSERT INTO PROD_IN_PLATFORM (ID, ID_PRODUCTION, ID_PLATFORM) 
VALUES (S_PROD_IN_PLATFORM.NEXTVAL, 20, 8);

INSERT INTO PROD_IN_PLATFORM (ID, ID_PRODUCTION, ID_PLATFORM) 
VALUES (S_PROD_IN_PLATFORM.NEXTVAL, 21, 5);

INSERT INTO PROD_IN_PLATFORM (ID, ID_PRODUCTION, ID_PLATFORM) 
VALUES (S_PROD_IN_PLATFORM.NEXTVAL, 22, 4);

INSERT INTO PROD_IN_PLATFORM (ID, ID_PRODUCTION, ID_PLATFORM) 
VALUES (S_PROD_IN_PLATFORM.NEXTVAL, 23, 8);

INSERT INTO PROD_IN_PLATFORM (ID, ID_PRODUCTION, ID_PLATFORM) 
VALUES (S_PROD_IN_PLATFORM.NEXTVAL, 24, 7);

INSERT INTO PROD_IN_PLATFORM (ID, ID_PRODUCTION, ID_PLATFORM) 
VALUES (S_PROD_IN_PLATFORM.NEXTVAL, 25, 4);

INSERT INTO PROD_IN_PLATFORM (ID, ID_PRODUCTION, ID_PLATFORM) 
VALUES (S_PROD_IN_PLATFORM.NEXTVAL, 26, 6);

INSERT INTO PROD_IN_PLATFORM (ID, ID_PRODUCTION, ID_PLATFORM) 
VALUES (S_PROD_IN_PLATFORM.NEXTVAL, 27, 6);

INSERT INTO PROD_IN_PLATFORM (ID, ID_PRODUCTION, ID_PLATFORM) 
VALUES (S_PROD_IN_PLATFORM.NEXTVAL, 28, 4);

INSERT INTO PROD_IN_PLATFORM (ID, ID_PRODUCTION, ID_PLATFORM) 
VALUES (S_PROD_IN_PLATFORM.NEXTVAL, 29, 4);

INSERT INTO PROD_IN_PLATFORM (ID, ID_PRODUCTION, ID_PLATFORM) 
VALUES (S_PROD_IN_PLATFORM.NEXTVAL, 30, 5);

INSERT INTO PROD_IN_PLATFORM (ID, ID_PRODUCTION, ID_PLATFORM) 
VALUES (S_PROD_IN_PLATFORM.NEXTVAL, 31, 5);

INSERT INTO PROD_IN_PLATFORM (ID, ID_PRODUCTION, ID_PLATFORM) 
VALUES (S_PROD_IN_PLATFORM.NEXTVAL, 32, 6);

INSERT INTO PROD_IN_PLATFORM (ID, ID_PRODUCTION, ID_PLATFORM) 
VALUES (S_PROD_IN_PLATFORM.NEXTVAL, 33, 6);

INSERT INTO PROD_IN_PLATFORM (ID, ID_PRODUCTION, ID_PLATFORM) 
VALUES (S_PROD_IN_PLATFORM.NEXTVAL, 34, 6);

INSERT INTO PROD_IN_PLATFORM (ID, ID_PRODUCTION, ID_PLATFORM) 
VALUES (S_PROD_IN_PLATFORM.NEXTVAL, 35, 6);

INSERT INTO PROD_IN_PLATFORM (ID, ID_PRODUCTION, ID_PLATFORM) 
VALUES (S_PROD_IN_PLATFORM.NEXTVAL, 36, 2);

INSERT INTO PROD_IN_PLATFORM (ID, ID_PRODUCTION, ID_PLATFORM) 
VALUES (S_PROD_IN_PLATFORM.NEXTVAL, 37, 2);

INSERT INTO PROD_IN_PLATFORM (ID, ID_PRODUCTION, ID_PLATFORM) 
VALUES (S_PROD_IN_PLATFORM.NEXTVAL, 38, 6);

INSERT INTO PROD_IN_PLATFORM (ID, ID_PRODUCTION, ID_PLATFORM) 
VALUES (S_PROD_IN_PLATFORM.NEXTVAL, 39, 5);

INSERT INTO PROD_IN_PLATFORM (ID, ID_PRODUCTION, ID_PLATFORM) 
VALUES (S_PROD_IN_PLATFORM.NEXTVAL, 40, 6);

INSERT INTO PROD_IN_PLATFORM (ID, ID_PRODUCTION, ID_PLATFORM) 
VALUES (S_PROD_IN_PLATFORM.NEXTVAL, 41, 6);

INSERT INTO PROD_IN_PLATFORM (ID, ID_PRODUCTION, ID_PLATFORM) 
VALUES (S_PROD_IN_PLATFORM.NEXTVAL, 42, 3);

INSERT INTO PROD_IN_PLATFORM (ID, ID_PRODUCTION, ID_PLATFORM) 
VALUES (S_PROD_IN_PLATFORM.NEXTVAL, 43, 6);

INSERT INTO PROD_IN_PLATFORM (ID, ID_PRODUCTION, ID_PLATFORM) 
VALUES (S_PROD_IN_PLATFORM.NEXTVAL, 44, 5);

INSERT INTO PROD_IN_PLATFORM (ID, ID_PRODUCTION, ID_PLATFORM) 
VALUES (S_PROD_IN_PLATFORM.NEXTVAL, 45, 4);

INSERT INTO PROD_IN_PLATFORM (ID, ID_PRODUCTION, ID_PLATFORM) 
VALUES (S_PROD_IN_PLATFORM.NEXTVAL, 46, 9);

INSERT INTO PROD_IN_PLATFORM (ID, ID_PRODUCTION, ID_PLATFORM) 
VALUES (S_PROD_IN_PLATFORM.NEXTVAL, 47, 6);

INSERT INTO PROD_IN_PLATFORM (ID, ID_PRODUCTION, ID_PLATFORM) 
VALUES (S_PROD_IN_PLATFORM.NEXTVAL, 48, 9);

INSERT INTO PROD_IN_PLATFORM (ID, ID_PRODUCTION, ID_PLATFORM) 
VALUES (S_PROD_IN_PLATFORM.NEXTVAL, 49, 7);

INSERT INTO PROD_IN_PLATFORM (ID, ID_PRODUCTION, ID_PLATFORM) 
VALUES (S_PROD_IN_PLATFORM.NEXTVAL, 50, 3);

INSERT INTO PROD_IN_PLATFORM (ID, ID_PRODUCTION, ID_PLATFORM) 
VALUES (S_PROD_IN_PLATFORM.NEXTVAL, 51, 6);

INSERT INTO PROD_IN_PLATFORM (ID, ID_PRODUCTION, ID_PLATFORM) 
VALUES (S_PROD_IN_PLATFORM.NEXTVAL, 52, 2);

INSERT INTO PROD_IN_PLATFORM (ID, ID_PRODUCTION, ID_PLATFORM) 
VALUES (S_PROD_IN_PLATFORM.NEXTVAL, 53, 8);

INSERT INTO PROD_IN_PLATFORM (ID, ID_PRODUCTION, ID_PLATFORM) 
VALUES (S_PROD_IN_PLATFORM.NEXTVAL, 54, 2);

INSERT INTO PROD_IN_PLATFORM (ID, ID_PRODUCTION, ID_PLATFORM) 
VALUES (S_PROD_IN_PLATFORM.NEXTVAL, 55, 2);

INSERT INTO PROD_IN_PLATFORM (ID, ID_PRODUCTION, ID_PLATFORM) 
VALUES (S_PROD_IN_PLATFORM.NEXTVAL, 56, 2);

INSERT INTO PROD_IN_PLATFORM (ID, ID_PRODUCTION, ID_PLATFORM) 
VALUES (S_PROD_IN_PLATFORM.NEXTVAL, 57, 2);

INSERT INTO PROD_IN_PLATFORM (ID, ID_PRODUCTION, ID_PLATFORM) 
VALUES (S_PROD_IN_PLATFORM.NEXTVAL, 58, 2);

INSERT INTO PROD_IN_PLATFORM (ID, ID_PRODUCTION, ID_PLATFORM) 
VALUES (S_PROD_IN_PLATFORM.NEXTVAL, 59, 2);

INSERT INTO PROD_IN_PLATFORM (ID, ID_PRODUCTION, ID_PLATFORM) 
VALUES (S_PROD_IN_PLATFORM.NEXTVAL, 60, 2);

