INSERT INTO MOVIE (ID_MOVIE) 
VALUES (1);

INSERT INTO MOVIE (ID_MOVIE) 
VALUES (2);

INSERT INTO MOVIE (ID_MOVIE) 
VALUES (3);

INSERT INTO MOVIE (ID_MOVIE) 
VALUES (4);

INSERT INTO MOVIE (ID_MOVIE) 
VALUES (5);

INSERT INTO MOVIE (ID_MOVIE) 
VALUES (6);

INSERT INTO MOVIE (ID_MOVIE) 
VALUES (7);

INSERT INTO MOVIE (ID_MOVIE) 
VALUES (8);

INSERT INTO MOVIE (ID_MOVIE) 
VALUES (9);

INSERT INTO MOVIE (ID_MOVIE) 
VALUES (10);

INSERT INTO MOVIE (ID_MOVIE) 
VALUES (11);

INSERT INTO MOVIE (ID_MOVIE) 
VALUES (12);

INSERT INTO MOVIE (ID_MOVIE) 
VALUES (13);

INSERT INTO MOVIE (ID_MOVIE) 
VALUES (14);

INSERT INTO MOVIE (ID_MOVIE) 
VALUES (15);

INSERT INTO MOVIE (ID_MOVIE) 
VALUES (16);

INSERT INTO MOVIE (ID_MOVIE) 
VALUES (17);

INSERT INTO MOVIE (ID_MOVIE) 
VALUES (18);

INSERT INTO MOVIE (ID_MOVIE) 
VALUES (19);

INSERT INTO MOVIE (ID_MOVIE) 
VALUES (20);

INSERT INTO MOVIE (ID_MOVIE) 
VALUES (21);

INSERT INTO MOVIE (ID_MOVIE) 
VALUES (22);

INSERT INTO MOVIE (ID_MOVIE) 
VALUES (23);

INSERT INTO MOVIE (ID_MOVIE) 
VALUES (24);

INSERT INTO MOVIE (ID_MOVIE) 
VALUES (25);

INSERT INTO MOVIE (ID_MOVIE) 
VALUES (26);

INSERT INTO MOVIE (ID_MOVIE) 
VALUES (27);

INSERT INTO MOVIE (ID_MOVIE) 
VALUES (28);

INSERT INTO MOVIE (ID_MOVIE) 
VALUES (29);

INSERT INTO MOVIE (ID_MOVIE) 
VALUES (30);

INSERT INTO MOVIE (ID_MOVIE) 
VALUES (31);

INSERT INTO MOVIE (ID_MOVIE) 
VALUES (32);

INSERT INTO MOVIE (ID_MOVIE) 
VALUES (33);

INSERT INTO MOVIE (ID_MOVIE) 
VALUES (34);

INSERT INTO MOVIE (ID_MOVIE) 
VALUES (35);

INSERT INTO MOVIE (ID_MOVIE) 
VALUES (36);

INSERT INTO MOVIE (ID_MOVIE) 
VALUES (37);

INSERT INTO MOVIE (ID_MOVIE) 
VALUES (38);

INSERT INTO MOVIE (ID_MOVIE) 
VALUES (39);

INSERT INTO MOVIE (ID_MOVIE) 
VALUES (40);

INSERT INTO MOVIE (ID_MOVIE) 
VALUES (41);

INSERT INTO MOVIE (ID_MOVIE) 
VALUES (42);

INSERT INTO MOVIE (ID_MOVIE) 
VALUES (43);

INSERT INTO MOVIE (ID_MOVIE) 
VALUES (44);

INSERT INTO MOVIE (ID_MOVIE) 
VALUES (45);

INSERT INTO MOVIE (ID_MOVIE) 
VALUES (46);

INSERT INTO MOVIE (ID_MOVIE) 
VALUES (47);

INSERT INTO MOVIE (ID_MOVIE) 
VALUES (48);

INSERT INTO MOVIE (ID_MOVIE) 
VALUES (49);

INSERT INTO MOVIE (ID_MOVIE) 
VALUES (50);

INSERT INTO MOVIE (ID_MOVIE) 
VALUES (51);

INSERT INTO MOVIE (ID_MOVIE) 
VALUES (53);

INSERT INTO MOVIE (ID_MOVIE) 
VALUES (61);




