INSERT INTO PARENT_OF(ID, id_parent, id_child) 
VALUES(S_PARENT_OF.NEXTVAL, 40, 45);

INSERT INTO PARENT_OF(ID, id_parent, id_child) 
VALUES(S_PARENT_OF.NEXTVAL, 40, 45);

INSERT INTO PARENT_OF(ID, id_parent, id_child) 
VALUES(S_PARENT_OF.NEXTVAL, 40, 46);

INSERT INTO PARENT_OF(ID, id_parent, id_child) 
VALUES(S_PARENT_OF.NEXTVAL, 40, 47);

INSERT INTO PARENT_OF(ID, id_parent, id_child) 
VALUES(S_PARENT_OF.NEXTVAL, 40, 48);

INSERT INTO PARENT_OF(ID, id_parent, id_child) 
VALUES(S_PARENT_OF.NEXTVAL, 40, 49);

INSERT INTO PARENT_OF(ID, id_parent, id_child) 
VALUES(S_PARENT_OF.NEXTVAL, 33, 45);

INSERT INTO PARENT_OF(ID, id_parent, id_child) 
VALUES(S_PARENT_OF.NEXTVAL, 33, 45);

INSERT INTO PARENT_OF(ID, id_parent, id_child) 
VALUES(S_PARENT_OF.NEXTVAL, 33, 46);

INSERT INTO PARENT_OF(ID, id_parent, id_child) 
VALUES(S_PARENT_OF.NEXTVAL, 33, 47);

INSERT INTO PARENT_OF(ID, id_parent, id_child) 
VALUES(S_PARENT_OF.NEXTVAL, 33, 48);

INSERT INTO PARENT_OF(ID, id_parent, id_child) 
VALUES(S_PARENT_OF.NEXTVAL, 33, 49);

